name: GitHub Classroom Workflow

on: [push]
env: 
      BUILD_TYPE: Release 

jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        strategy:
              max-parallel: 1
        steps:
          - uses: actions/checkout@v2
          - name: build
            run: sh build.sh
          - uses : hikmatfarhat-ndu/my_autograding@main
          - uses: actions/upload-artifact@v2
            with:
                  name: report
                  path: report.md
         # - uses: EndBug/add-and-commit@v5
         #   with:
         #      add: "*"
         #   env: 
         #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
      status:
        name: status
        runs-on: ubuntu-latest
        needs: [build]
        steps:
              - uses: actions/checkout@v2
              - uses: actions/download-artifact@v2
                with:
                      name: report
              - name: status
                run: sh status.sh
              
