name: GitHub Classroom Workflow

on: [push]
env: 
      BUILD_TYPE: Release 

jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: build
            run: sh build.sh
          - name: test
            run: sh testAll.sh
#          - uses: education/autograding@v1
#          - uses : hikmatfarhat-ndu/my_autograding@main
