name: GitHub Classroom Workflow

on: [workflow_dispatch,issue_comment]
env: 
      BUILD_TYPE: Release 

jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
     #   if: ${{(github.event.issue.pull_request) && contains(github.event.comment.body,'/eval')}}
        strategy:
              max-parallel: 1
        steps:
          - uses: actions/checkout@v2
          - name: greeting
            run: gh pr comment ${{github.event.issue_number}} -b "Please wait a few minutes. The grade will be displayed below"
            env:
                 GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          - name: build
            run: sh build.sh
          - name: autograding
            uses : hikmatfarhat-ndu/my_autograding@main
          - name: status
            run: sh status.sh
            env:
               GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          - uses: actions/upload-artifact@v2
            if: ${{always()}}
            with:
                  name: report
                  path: report.md
         # - uses: EndBug/add-and-commit@v5
         #   with:
         #      add: "*"
         #   env: 
         #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
     # status:
     #   name: status
     #   runs-on: ubuntu-latest
     #   needs: [build]
        #if: "!contains(github.event.head_commit.message, 'GitHub')"
        # for some reason the below does not work
        #if: "!contains(github.event.actor,'github-classroom')"
     #   if : github.event.run_number > 4
     #   steps:
     #         - uses: actions/checkout@v2
              #- name: environ
              #  run: env
      #        - uses: actions/download-artifact@v2
       #         with:
        #              name: report
         #     - name: status
          #      run: sh status.sh
         #       env:
         #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              
