name: GitHub Classroom Workflow

on: [push]
env: 
      BUILD_TYPE: Release 

jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        strategy:
              max-parallel: 1
        steps:
          - uses: actions/checkout@v2
          - name: build
            run: sh build.sh
          - uses : hikmatfarhat-ndu/my_autograding@main
          - uses: EndBug/add-and-commit@v5
            with:
               add: "*"
            env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
